--require("indent_blankline").setup {
--    -- for example, context is off by default, use this to turn it on
--    show_current_context = false,
--    show_current_context_start = false,
--}
--
--require("indent_blankline").setup {
--    show_end_of_line = true,
--}
